# Default values for app1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3 
app:
  port: 8000
  host: '0.0.0.0'
  workers: 4

image:
  repository: 'foobarqix'
  tag: '0.1.0'
  digest: sha256:e4154f33e5210137c8dbc593afa357cc1cb969967d6ea3431a32ff9565a4e586
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  host:
    name: foobarqix.kubernetes.local
    paths: [/]

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
