apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foobarqix
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:r2r-dev/foobarqix.git
    targetRevision: HEAD
    path: charts/foobarqix
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}

