apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: git@github.com:r2r-dev/foobarquix
      sshPrivateKeySecret:
        name: argocd-repository-secret
        key: ssh-privatekey

