#In prod scenario this file should be encrypted, or generated on the fly via 3rdparty secret vault. One could use kops, sealed secrets, gitcrypt, etc.
apiVersion: v1
data:
  id_rsa.pub: aHR0cHM6Ly9zdWJzY3JpcHRpb25zLmdpci5zdC93YXRjaD92PWl6R3dEc3JRMWVRJnNob3c9cmF3
  ssh-privatekey: aHR0cHM6Ly9zdWJzY3JpcHRpb25zLmdpci5zdC93YXRjaD92PWRRdzR3OVdnWGNRJnNob3c9cmF3
kind: Secret
type: kubernetes.io/ssh-auth
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  creationTimestamp: null
  name: argocd-repository-secret
