apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foobarquix
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:r2r-dev/foobarquix.git
    targetRevision: HEAD
    path: charts/foobarquix
  destination:
    server: https://kubernetes.default.svc
    namespace: foobarquix
  syncPolicy:
    # https://github.com/argoproj/argo-cd/issues/3490#issuecomment-732384194
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true

