apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foobarquix.fullname" . }}
  labels: 
{{ include "foobarquix.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "foobarquix.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "foobarquix.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "foobarquix.name" . }}
      containers:
        - name: {{ .Chart.Name }} 
          {{- with .Values.image }}
          # https://github.com/kubernetes/minikube/issues/8867#issuecomment-734681387
          image: "{{.repository}}{{- if (.tag) -}} :{{.tag}} {{- else -}} @{{.digest}} {{- end -}}"
          {{- end }}
          ports:
            - containerPort: {{ .Values.app.port }} 
          envFrom:
            - configMapRef:
                name: {{ include "foobarquix.fullname" . }}
          livenessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.app.port }}
            initialDelaySeconds: 3
            periodSeconds: 3

