apiVersion: v1
appVersion: "0.1.0"
description: A Helm chart for FooBarQuix
home: https://github.com/r2r-dev/foobarquix
maintainers:
- email: dev@r2r.sh
  name: Artur Stachecki
name: foobarquix
version: "0.1.0"
